### ISSUE TITLE
GPUS on CentOS

### ISSUE THREAD

**Issue by simonlvr** [fananimi/rqd-gcp#1]
Hi!

Great work on the RQD. I tried (without success unfortunately) to deploy on Google Cloud on an Ubuntu 18.04 instance, but I'm having trouble getting the RQD fired up and working properly within this environment.

https://cloud.google.com/solutions/creating-a-render-farm-on-gcp-using-opencue

Are you still working on this? Do you have any further documentation?

I tried running it as per the usage instructions but only get this far:

```
Step 7/44 : COPY build/nvidia/cuda/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb .
COPY failed: stat /var/lib/docker/tmp/docker-builder826608525/build/nvidia/cuda/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb: no such file or directory
```

Thanks,

Simon

**Comment by fananimi** [comment]
Hi @simonlvr , the problem occured because you do not have a sets of dependencies. You can build the image container with the following commands

`make build`

Thanks.
